; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v2 on Wed Jan 30 2019 23:28:53 GMT+1100 (AEDT)
G10                  ; retract
G4 P2000             ; wait 2s
;M98 P"prime.g"
G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0          ; go back to the last print move
M83                  ; relative extruder moves
G11                  ; unretract
